[package]
name = "rulox"
version = "0.1.0"
edition = "2021"


[dependencies]
enum-display = "0.1.3"
enum-display-derive = "0.1.1"
itertools = "0.12.0"
paste = "1.0.14"
pate = "0.0.1"
peekmore = "1.3.0"
thiserror = "1.0.56"
