[package]
name = "rulox"
version = "0.1.0"
edition = "2021"


[dependencies]
assert2 = "0.3.11"
clap = { version = "4.4.18", features = ["derive"] }
enum-display = "0.1.3"
enum-display-derive = "0.1.1"
itertools = "0.12.0"
peekmore = "1.3.0"
thiserror = "1.0.56"
